# Enable the subsequent settings only in interactive sessions
case $- in
  *i*) ;;
    *) return;;
esac

export OSH=~/.oh-my-bash
OSH_THEME="bakke"

OMB_USE_SUDO=true
OMB_PROMPT_SHOW_PYTHON_VENV=true

completions=(
  git
  docker
  ssh
  makefile
  pip
  system
)

aliases=(
  general
  docker
)

plugins=(
  git
  fasd
  sudo
)

source "$OSH"/oh-my-bash.sh

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

if [ -f "$HOME/.bash_env" ]; then
    source "$HOME/.bash_env"
fi

# Set default editor to vim
export EDITOR=vim

# Enable incremental search using arrow keys
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/malici/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/malici/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/malici/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/malici/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


fasd_cache="$HOME/.fasd-init-bash"
if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
  fasd --init posix-alias bash-hook bash-ccomp bash-ccomp-install >| "$fasd_cache"
fi
source "$fasd_cache"
unset fasd_cache
_fasd_bash_hook_cmd_complete v m j o
