#!/usr/bin/env bash

# Set color variables
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

set -e  # Exit immediately if a command exits with a non-zero status

# Starting the test suite
echo -e "${CYAN}Starting tests...${NC}"

# Simulate interactive shell for tests and explicitly source the bashrc file
bash --init-file ~/.bashrc -i tests/test.sh

echo -e "${GREEN}All tests passed successfully.${NC}"