#!/usr/bin/env bash

# Color variables
BLUE='\033[1;34m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# URL for downloading VSCode
VSCODE_URL="https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

# List of VSCode extensions to install
VSCODE_EXTENSIONS=(
    "ms-python.python"
    "GitHub.copilot"
    "ms-azuretools.vscode-docker"
    "ms-vscode-remote.remote-ssh"
    "github.vscode-github-actions"
)

# Check if not running in WSL2 before installing Visual Studio Code
if ! grep -q microsoft /proc/version; then
    echo -e "\n${BLUE}INFO: Install VS Code${NC}"
    echo -e "${GREEN} - Not running in WSL2. Proceeding with Visual Studio Code installation...${NC}"

    # Create the downloads directory if it doesn't exist
    mkdir -p ~/downloads
    echo -e "${GREEN} - Created ~/downloads directory (if not already present).${NC}"

    # Download the VSCode deb package
    echo -e "${GREEN} - Downloading Visual Studio Code...${NC}"
    wget "$VSCODE_URL" -O ~/downloads/vscode.deb

    # Install the downloaded VSCode package
    echo -e "${GREEN} - Installing Visual Studio Code...${NC}"
    sudo apt install -y ~/downloads/vscode.deb

    # Install VSCode extensions
    echo -e "${GREEN} - Installing VSCode extensions...${NC}"
    for extension in "${VSCODE_EXTENSIONS[@]}"; do
        code --install-extension "$extension"
        echo -e "${GREEN}   -> Installed: $extension${NC}"
    done

    echo -e "${GREEN} - VSCode and all extensions installed successfully!${NC}\n"
else
    echo -e "\n${YELLOW}INFO: WSL2 Detected${NC}"
    echo -e "${YELLOW} - Skipping Visual Studio Code installation as the system is running in WSL2.${NC}\n"
fi
