name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t dotfiles-test-image:latest .

      - name: Run Docker Container and Execute Tests
        run: |
          # Run the container
          docker run --rm --name test-container my-dotfiles-image:latest \
          || (echo "Tests failed"; exit 1)